# Teascript Language Extension for Zed
id = "teascript"
name = "Teascript"
description = "Teascript support."
version = "0.1.0"
schema_version = 1
repository = "https://github.com/revengerwizard/zed-teascript"
authors = ["Wizard"]

[grammars.teascript]
repository = "https://github.com/revengerwizard/tree-sitter-teascript"
rev = "9845700977567bd4cb7b26fde1118bbbce16fec1"